
services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: hossain/php
    container_name: app
    volumes:
      - ./SchoolManagement:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schoolmanagement.com 
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

