
services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: hossain/schoolmanagement
    ports:
      - 9000:80
  
  mysql_db:
    image: mysql:latest
    environment:
     - MYSQL_DATABASE=${DB_DATABASE}
     - MYSQL_USER=${DB_USERNAME}
     - MYSQL_PASSWORD=${DB_PASSWORD}
     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} 
    ports:
      - 3308:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

